framework:
    secret: '%env(APP_SECRET)%'
    session: ~
    validation: { enabled: true, enable_annotations: true }
twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']

tactician:
    default_bus: command
    method_inflector: tactician.handler.method_name_inflector.invoke
    commandbus:
        query:
            middleware:
                - tactician.commandbus.query.middleware.command_handler
        command:
            middleware:
                - tactician.commandbus.command.middleware.command_handler
enqueue:
    transport:
        default: '%rabbitmq_dsn%'
    client: ~
